//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskStatusLog
    {
        public int Id { get; set; }
        public int TaskId { get; set; }
        public int StatusId { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual TaskStatus TaskStatus { get; set; }
    }
}
